// Generated by tools/generate_caption_icons.py. Do not edit manually.
// Copyright 2016 The Chromium Authors. BSD license and original paths:
// third_party/chromium_caption/LICENSE and third_party/chromium_caption/*.icon
#pragma once
#include <string_view>

namespace ChromiumCaptionIcons {
    inline constexpr int representationSize(int pixels) {
        // Chromium's exact-match / largest-divisor / next-larger policy.
        if (pixels <= 12 || (pixels % 12 == 0 && pixels % 24 != 0))
            return 12;
        return 24;
    }

    inline constexpr std::string_view svg(std::string_view name, int pixels) {
        if (pixels < 1)
            return {};
        const bool small = representationSize(pixels) == 12;
        if (name == "window-minimize-symbolic")
            return small ? R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" d="M1 9h10v2H1Z"/></svg>)icon" : R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M1 20h22v3H1Z"/></svg>)icon";
        if (name == "window-maximize-symbolic")
            return small ? R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" d="M11 1v10H1V1h10ZM9 9H3V3h6v6Z"/></svg>)icon" : R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M23 1v22H1V1h22Zm-3 19H4V4h16v16Z"/></svg>)icon";
        if (name == "window-restore-symbolic")
            return small ? R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" d="M11 8H4V1h7v7ZM6 6V3h3v3H6ZM3 3H1v8h8V9H3V3Z"/></svg>)icon" : R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M23 16H8V1h15v15Zm-12 -3V4h9v9h-9ZM4 8H1v15h15v-3H4V8Z"/></svg>)icon";
        if (name == "window-close-symbolic")
            return small ? R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" d="M6 4.59L2.46 1.05L1.05 2.46L4.59 6L1.05 9.54l1.41 1.41L6 7.41l3.54 3.54l1.41 -1.41L7.41 6l3.54 -3.54L9.54 1.05L6 4.59Z"/></svg>)icon" : R"icon(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M23 3.22L20.78 1L12 9.78L3.22 1L1 3.22L9.78 12L1 20.78L3.22 23L12 14.22L20.78 23L23 20.78L14.22 12L23 3.22Z"/></svg>)icon";
        return {};
    }
}
