#!/usr/bin/env python3
"""Convert the vendored Chromium caption paths to embedded SVG (no network)."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "third_party/chromium_caption"
OUTPUT = ROOT / "ChromiumCaptionIcons.hpp"
COMMANDS = {
    "MOVE_TO": ("M", 2), "R_MOVE_TO": ("m", 2),
    "LINE_TO": ("L", 2), "R_LINE_TO": ("l", 2),
    "H_LINE_TO": ("H", 1), "R_H_LINE_TO": ("h", 1),
    "V_LINE_TO": ("V", 1), "R_V_LINE_TO": ("v", 1),
    "CLOSE": ("Z", 0),
}


def svg_reps(path):
    source = re.sub(r"//[^\n]*", "", path.read_text())
    tokens = [s.strip() for s in source.replace("\n", ",").split(",") if s.strip()]
    result = {}
    canvas, commands = None, []
    i = 0
    while i < len(tokens):
        op = tokens[i]
        i += 1
        if op == "CANVAS_DIMENSIONS":
            if canvas is not None:
                result[canvas] = "".join(commands)
            canvas = int(tokens[i])
            i += 1
            commands = []
            continue
        letter, count = COMMANDS[op]  # fail rather than silently losing a path
        args = tokens[i:i + count]
        assert len(args) == count
        for value in args:
            float(value)  # ensure only numeric path arguments are emitted
        commands.append(letter + " ".join(args))
        i += count
    result[canvas] = "".join(commands)
    assert set(result) == {12, 24}
    return {size: f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}"><path fill-rule="evenodd" d="{data}"/></svg>'
            for size, data in result.items()}


text = """// Generated by tools/generate_caption_icons.py. Do not edit manually.
// Copyright 2016 The Chromium Authors. BSD license and original paths:
// third_party/chromium_caption/LICENSE and third_party/chromium_caption/*.icon
#pragma once
#include <string_view>

namespace ChromiumCaptionIcons {
    inline constexpr int representationSize(int pixels) {
        // Chromium's exact-match / largest-divisor / next-larger policy.
        if (pixels <= 12 || (pixels % 12 == 0 && pixels % 24 != 0))
            return 12;
        return 24;
    }

    inline constexpr std::string_view svg(std::string_view name, int pixels) {
        if (pixels < 1)
            return {};
        const bool small = representationSize(pixels) == 12;
"""
for action in ("minimize", "maximize", "restore", "close"):
    reps = svg_reps(SOURCES / f"window_control_{action}_old.icon")
    text += f'        if (name == "window-{action}-symbolic")\n'
    text += f'            return small ? R"icon({reps[12]})icon" : R"icon({reps[24]})icon";\n'
text += "        return {};\n    }\n}\n"
if "--check" in sys.argv:
    assert OUTPUT.read_text() == text, "Run tools/generate_caption_icons.py to update the header"
    print("Chromium caption vectors match their upstream source paths")
else:
    OUTPUT.write_text(text)
